# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kravemir.org
email: mail@kravemir.org.invalid
description: > # this means to ignore newlines until "baseurl:"
    Personal blog, and site about me and projects I'm developing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  kravemir


# Posts Settings
permalink: /posts/:year/:title
author_name: Miroslav Kravec

# Build settings
markdown: kramdown
